version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/sevenworks"
    schedule:
      interval: "weekly"
    ignore:
      # Ignoring pdfjs-dist because we've implemented code-level mitigations through SecurePdfViewer component
      - dependency-name: "pdfjs-dist"
        versions:
          - "< 5.0.0"